"""Initial schema with all tables

Revision ID: 8dbb07d195b9
Revises: 
Create Date: 2026-01-09 12:36:38.548735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dbb07d195b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name_he', sa.String(), nullable=True),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_types_code'), 'asset_types', ['code'], unique=True)
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('linked_type', sa.String(), nullable=False),
    sa.Column('linked_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('uploaded_by_actor_type', sa.String(), nullable=False),
    sa.Column('uploaded_by_actor_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_by_actor_display', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_created_at'), 'attachments', ['created_at'], unique=False)
    op.create_index(op.f('ix_attachments_linked_id'), 'attachments', ['linked_id'], unique=False)
    op.create_index(op.f('ix_attachments_linked_type'), 'attachments', ['linked_type'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('main_address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_table('internal_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'TECHNICIAN', 'OFFICE', name='internaluserrole'), nullable=False),
    sa.Column('preferred_locale', sa.Enum('HE_IL', 'EN_US', name='locale'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_users_email'), 'internal_users', ['email'], unique=True)
    op.create_table('internet_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('name_he', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internet_providers_name'), 'internet_providers', ['name'], unique=True)
    op.create_table('ticket_status_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name_he', sa.String(), nullable=True),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_closed_state', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_status_definitions_code'), 'ticket_status_definitions', ['code'], unique=True)
    op.create_table('asset_property_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_type_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('label_he', sa.String(), nullable=True),
    sa.Column('label_en', sa.String(), nullable=True),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('visibility', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_type_id', 'key', name='uq_asset_property_definition_type_key')
    )
    op.create_index(op.f('ix_asset_property_definitions_asset_type_id'), 'asset_property_definitions', ['asset_type_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_client_id'), 'contacts', ['client_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_end_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('created_by_actor_type', sa.String(), nullable=False),
    sa.Column('created_by_actor_id', sa.UUID(), nullable=True),
    sa.Column('created_by_actor_display', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_client_id'), 'projects', ['client_id'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_client_id'), 'sites', ['client_id'], unique=False)
    op.create_table('client_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('CLIENT_CONTACT', 'CLIENT_ADMIN', name='clientuserrole'), nullable=False),
    sa.Column('preferred_locale', sa.Enum('HE_IL', 'EN_US', name='locale'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_users_client_id'), 'client_users', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_users_email'), 'client_users', ['email'], unique=True)
    op.create_table('contact_site_links',
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact_id', 'site_id')
    )
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('building', sa.String(), nullable=True),
    sa.Column('floor', sa.String(), nullable=True),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_site_id'), 'locations', ['site_id'], unique=False)
    op.create_table('project_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_display', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_events_created_at'), 'project_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_project_events_project_id'), 'project_events', ['project_id'], unique=False)
    op.create_table('project_site_links',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'site_id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_number', sa.String(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('source_channel', sa.String(), nullable=False),
    sa.Column('reported_via', sa.String(), nullable=True),
    sa.Column('status_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to_internal_user_id', sa.UUID(), nullable=True),
    sa.Column('service_scope', sa.String(), nullable=False),
    sa.Column('service_note', sa.Text(), nullable=True),
    sa.Column('contact_person_id', sa.UUID(), nullable=True),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=False),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_internal_user_id'], ['internal_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contact_person_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['status_id'], ['ticket_status_definitions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_assigned_to_internal_user_id'), 'tickets', ['assigned_to_internal_user_id'], unique=False)
    op.create_index(op.f('ix_tickets_client_id'), 'tickets', ['client_id'], unique=False)
    op.create_index(op.f('ix_tickets_site_id'), 'tickets', ['site_id'], unique=False)
    op.create_index(op.f('ix_tickets_status_id'), 'tickets', ['status_id'], unique=False)
    op.create_index(op.f('ix_tickets_ticket_number'), 'tickets', ['ticket_number'], unique=True)
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('asset_type_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_type_id'), 'assets', ['asset_type_id'], unique=False)
    op.create_index(op.f('ix_assets_client_id'), 'assets', ['client_id'], unique=False)
    op.create_index(op.f('ix_assets_serial_number'), 'assets', ['serial_number'], unique=False)
    op.create_index(op.f('ix_assets_site_id'), 'assets', ['site_id'], unique=False)
    op.create_table('project_ticket_links',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'ticket_id')
    )
    op.create_table('ticket_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_display', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_events_created_at'), 'ticket_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_ticket_events_ticket_id'), 'ticket_events', ['ticket_id'], unique=False)
    op.create_table('ticket_initiators',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('initiator_type', sa.String(), nullable=False),
    sa.Column('initiator_ref_id', sa.UUID(), nullable=True),
    sa.Column('initiator_display', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_table('work_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('work_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('included_in_service', sa.Boolean(), nullable=False),
    sa.Column('billing_note', sa.Text(), nullable=True),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_display', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_logs_created_at'), 'work_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_work_logs_ticket_id'), 'work_logs', ['ticket_id'], unique=False)
    op.create_table('asset_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_display', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_events_asset_id'), 'asset_events', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_events_created_at'), 'asset_events', ['created_at'], unique=False)
    op.create_table('asset_property_values',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('property_definition_id', sa.UUID(), nullable=False),
    sa.Column('value_string', sa.Text(), nullable=True),
    sa.Column('value_int', sa.Integer(), nullable=True),
    sa.Column('value_bool', sa.Boolean(), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('value_decimal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('value_enum', sa.String(), nullable=True),
    sa.Column('value_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_actor_type', sa.String(), nullable=False),
    sa.Column('updated_by_actor_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_actor_display', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_definition_id'], ['asset_property_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'property_definition_id', name='uq_asset_property_value_asset_definition')
    )
    op.create_index(op.f('ix_asset_property_values_asset_id'), 'asset_property_values', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_property_values_property_definition_id'), 'asset_property_values', ['property_definition_id'], unique=False)
    op.create_table('nvr_disks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=True),
    sa.Column('capacity_tb', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('install_date', sa.Date(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nvr_disks_asset_id'), 'nvr_disks', ['asset_id'], unique=False)
    op.create_table('project_asset_links',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'asset_id')
    )
    op.create_table('ticket_asset_links',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id', 'asset_id')
    )
    op.create_table('ticket_line_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('included_in_service', sa.Boolean(), nullable=False),
    sa.Column('chargeable', sa.Boolean(), nullable=False),
    sa.Column('external_reference', sa.String(), nullable=True),
    sa.Column('linked_asset_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_display', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['linked_asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_line_items_created_at'), 'ticket_line_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_ticket_line_items_ticket_id'), 'ticket_line_items', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_line_items_ticket_id'), table_name='ticket_line_items')
    op.drop_index(op.f('ix_ticket_line_items_created_at'), table_name='ticket_line_items')
    op.drop_table('ticket_line_items')
    op.drop_table('ticket_asset_links')
    op.drop_table('project_asset_links')
    op.drop_index(op.f('ix_nvr_disks_asset_id'), table_name='nvr_disks')
    op.drop_table('nvr_disks')
    op.drop_index(op.f('ix_asset_property_values_property_definition_id'), table_name='asset_property_values')
    op.drop_index(op.f('ix_asset_property_values_asset_id'), table_name='asset_property_values')
    op.drop_table('asset_property_values')
    op.drop_index(op.f('ix_asset_events_created_at'), table_name='asset_events')
    op.drop_index(op.f('ix_asset_events_asset_id'), table_name='asset_events')
    op.drop_table('asset_events')
    op.drop_index(op.f('ix_work_logs_ticket_id'), table_name='work_logs')
    op.drop_index(op.f('ix_work_logs_created_at'), table_name='work_logs')
    op.drop_table('work_logs')
    op.drop_table('ticket_initiators')
    op.drop_index(op.f('ix_ticket_events_ticket_id'), table_name='ticket_events')
    op.drop_index(op.f('ix_ticket_events_created_at'), table_name='ticket_events')
    op.drop_table('ticket_events')
    op.drop_table('project_ticket_links')
    op.drop_index(op.f('ix_assets_site_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_serial_number'), table_name='assets')
    op.drop_index(op.f('ix_assets_client_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_type_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_tickets_ticket_number'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_site_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_client_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_assigned_to_internal_user_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_table('project_site_links')
    op.drop_index(op.f('ix_project_events_project_id'), table_name='project_events')
    op.drop_index(op.f('ix_project_events_created_at'), table_name='project_events')
    op.drop_table('project_events')
    op.drop_index(op.f('ix_locations_site_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_table('contact_site_links')
    op.drop_index(op.f('ix_client_users_email'), table_name='client_users')
    op.drop_index(op.f('ix_client_users_client_id'), table_name='client_users')
    op.drop_table('client_users')
    op.drop_index(op.f('ix_sites_client_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_projects_client_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_contacts_client_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_asset_property_definitions_asset_type_id'), table_name='asset_property_definitions')
    op.drop_table('asset_property_definitions')
    op.drop_index(op.f('ix_ticket_status_definitions_code'), table_name='ticket_status_definitions')
    op.drop_table('ticket_status_definitions')
    op.drop_index(op.f('ix_internet_providers_name'), table_name='internet_providers')
    op.drop_table('internet_providers')
    op.drop_index(op.f('ix_internal_users_email'), table_name='internal_users')
    op.drop_table('internal_users')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_attachments_linked_type'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_linked_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_created_at'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_asset_types_code'), table_name='asset_types')
    op.drop_table('asset_types')
    # ### end Alembic commands ###
